[package]
name = "scoutnet"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.27.0"
tui-tree-widget = "0.21.0"
tui-textarea = "0.5.0"
pnet = "0.35.0"
tui-scrollview = "0.3.7"
tokio = { version = "1.28.0", features = ["full"] }
lazy_static = "1.5.0"