[package]
edition = "2021"
name = "scoutnet"
version = "0.1.0"

[dependencies]
lazy_static = "1.5.0"
pnet = "0.35.0"
ratatui = "0.27.0"
tokio = {version = "1.28.0", features = ["full"]}
tui-scrollview = "0.3.7"
tui-textarea = "0.5.0"
tui-tree-widget = "0.21.0"
